[package]
name = "unwind_aborts"
version = "0.1.0"
authors = ["Adam Gausmann <agausmann@fastmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2  = "1.0.9"
quote = "1.0.3"

[dependencies.syn]
version = "1.0.17"
features = [
    "full",
]
